# Generated by Django 5.0.6 on 2026-07-26 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sector', models.CharField(max_length=100)),
                ('reporting_year', models.IntegerField()),
                ('scope1_tco2e', models.FloatField(help_text='Direct emissions (owned/controlled sources)')),
                ('scope2_tco2e', models.FloatField(help_text='Indirect emissions from purchased energy')),
                ('scope3_tco2e', models.FloatField(blank=True, help_text='Other indirect value-chain emissions', null=True)),
                ('note', models.CharField(default='Illustrative sample data for demo purposes only, not an official disclosure.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('scope', models.CharField(choices=[('Scope 1', 'Scope 1 - Direct emissions'), ('Scope 2', 'Scope 2 - Purchased energy'), ('Scope 3', 'Scope 3 - Value chain')], max_length=10)),
                ('unit_type', models.CharField(choices=[('energy', 'Energy'), ('volume', 'Volume'), ('mass', 'Mass'), ('count', 'Count')], max_length=10)),
                ('base_unit', models.CharField(max_length=20)),
                ('factor_value', models.FloatField()),
                ('note', models.CharField(blank=True, default='Illustrative factor for demo purposes.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculator_type', models.CharField(max_length=50)),
                ('scope', models.CharField(choices=[('Scope 1', 'Scope 1 - Direct emissions'), ('Scope 2', 'Scope 2 - Purchased energy'), ('Scope 3', 'Scope 3 - Value chain')], default='Scope 1', max_length=10)),
                ('activity_value', models.FloatField(help_text='Raw value entered by the user')),
                ('input_unit', models.CharField(help_text='Unit the user entered activity_value in', max_length=20)),
                ('emission_factor', models.FloatField(help_text='kg CO2e per base unit, used for this calculation')),
                ('result', models.FloatField(help_text='Result in kg CO2e')),
                ('result_tonnes', models.FloatField(help_text='Result in tonnes CO2e (result / 1000)')),
                ('unit', models.CharField(default='kg CO2e', max_length=50)),
                ('period_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], default='Monthly', max_length=10)),
                ('period_year', models.IntegerField()),
                ('period_month', models.IntegerField(blank=True, help_text='1-12, used when period_type=Monthly', null=True)),
                ('period_quarter', models.IntegerField(blank=True, help_text='1-4, used when period_type=Quarterly', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculations', to='calculator.company')),
                ('emission_factor_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculator.emissionfactor')),
            ],
        ),
    ]
